### PR TITLE
Fix iso_staggered rendering

### PR DESCRIPTION
**Pull request by Affinator**
- fixed project_iso_staggered in helpers.rs
- I am not 100% sure if this is the correct fix

Please check if this change is fixing it the correct way. It is working on my side.

### CODE REVIEW

**Comment by bzm3r** [comment]
@Affinator Oh, good catch! I'll check this out, and make it a 100% correct solution in case it isn't already.

**Comment by bzm3r** [comment]
@Affinator can you check out the `hex-neighbours` branch now, to confirm that the problem is fixed? Thanks for your PR! It was a helpful hint in figuring out where the error lay, but I think the changes I made to `hex-neighbours` fix the problem in a more general way (the issue is ultimately with the definition of `project_iso_staggered` and `project_iso_diamond`).

**Comment by Affinator** [comment]
Still broken.

Now there is a gap between the chunks...
grafik

**Comment by bzm3r** [comment]
> Still broken.
> 
> Now there is a gap between the chunks... grafik

Weird, I thought I fixed precisely this issue....

Can I have a link to the example file that produces this?

Yeah, I am not able to reproduce this issue. I just tried out a quadrant size of 200, and am not seeing the gaps (in the iso diamond example)....

**Comment by bzm3r** [comment]
Yeah, I am not able to reproduce this issue. I just tried out a quadrant size of 200, and am not seeing the gaps (in the iso diamond example)....

**Comment by Affinator** [comment]
I just did a fresh git clone and checked out this branch and only edited the quadrant size of iso_staggered.rs to 80.
(The window descriptor is wrong.)

grafik

Edit: The main-branch at https://github.com/StarArawn/bevy_ecs_tilemap has the same problem.
Edit2: Iso-diamond is working as intended (even at large quadrant sizes).

**Comment by bzm3r** [comment]
> me problem.
> Edit2: Iso-diamond is working as intended (even at large quadrant sizes).

@Affinator Thank you! I was able to reproduce this, and I fixed the issue! Try it out now :D

**Pull request closed without merging**
